#!/usr/bin/env node

var fake = require('faker');
var fs = require('fs');

// var locales = ['de','en','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
var getSpecialism = function() {
  specialists = ["Specialist", "Professional", "Executive", "Engineer", "Technician"];
  return (specialists[Math.floor(Math.random() * specialists.length)]);
}
var URL = function() { return ("http://www." + fake.internet.domainName() +"/"+ fake.lorem.words(1)); };
var Company = function() { return (fake.company.bsAdjective() +" "+ fake.company.bsNoun())};
var Job = function() { return (fake.company.catchPhraseAdjective() +" "+ fake.company.catchPhraseNoun() + " " + getSpecialism()) };
var DisplayName = function() { return (fake.company.catchPhraseAdjective() + fake.hacker.noun())};
var CompanyName = function() { return (fake.company.bsNoun() + " " + fake.company.companySuffix())};

var fileType = "people"; // global until the logic is added for other types

if (!process.argv[2] || isNaN(+process.argv[2])) {
  console.log("Usage: generatePeople # "); //locale import")

} else { // only write a file if the user indicates how many records
  userInput = +process.argv[2];
    fake.locale = "en"; // manual entry for now
    var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

    stream.once('open', function(fd) {
      stream.write("Unique ID,First Name,Last Name,Display Name,Title,Bio,Email,Email 2,Organization Name,Website,Website 2,Address,Address 2,City,State,Zipcode,Country,Phone Work,Phone Mobile,Phone Other,Phone Other Type,Tags (comma-separated),Linkedin URL,Twitter URL,Facebook URL,Admin Invitations (Comma-separated)\n");

      for (i=0; i<userInput; i++) {
        stream.write("A-" + (i+1) + ", " + fake.name.firstName() + ", " + fake.name.lastName() + ", " + DisplayName() + ", " + Job() + ", " + fake.hacker.ingverb() + ", " + fake.internet.email() + ", " + fake.internet.email() + ", " + CompanyName() + ", " + URL() + ", " + URL() + ", " + fake.address.streetAddress() + ", " + fake.address.city() + ", " + fake.address.state() + ", " + fake.address.zipCode() + ", " + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + ", " + ", " + ", " + ",\n");
      }
      stream.end();
      console.log(fake.locale +"_"+ fileType + ".csv created");
    });
}
