#!/usr/bin/env node

var fake = require('faker');
var fs = require('fs');

// var All_locales = ['de', 'de_AT','de_CH','en','en_AU','en_BORK','en_CA','en_GB','en_IND','en_US','en_au_ocker','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
// var locales = ['de','en','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
var getSpecialism = function() {
  specialists = ["Specialist", "Professional", "Executive", "Engineer", "Technician"];
  return (specialists[Math.floor(Math.random() * specialists.length)]);
}
var URL = function() { return("http://www." + fake.internet.domainName() +"/"+ fake.lorem.words(1)); };
var Company = function() { return(fake.company.bsAdjective() +" "+ fake.company.bsNoun())};
var Job = function() { return(fake.company.catchPhraseAdjective() +" "+ fake.company.catchPhraseNoun() + getSpecialism()) };
var fileType = "invitees"; // global until the logic is added for other types

if (!process.argv[2] || isNaN(+process.argv[2])) {
  console.log("Usage: generatePages # "); //locale import")

} else { // only write a file if the user indicates how many records
  userInput = +process.argv[2];
    fake.locale = "zh_CN"; // manual entry for now
    var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

    stream.once('open', function(fd) {
      stream.write("Unique ID,Name,Description,Category Tags (Comma-separated)\n");
      for (i=0; i<userInput; i++) {
        stream.write("A-" + (i+1) +", "+ ", " + "<p>" + fake.company.catchPhrase() + "<br></p>" +", \n");
      }
      stream.end();
      console.log(fake.locale +"_"+ fileType + ".csv created");
    });
}
