#!/usr/bin/env node

var fake = require('faker');
var fs = require('fs');

// var locales = ['de','en','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
var getSpecialism = function() {
  specialists = ["Specialist", "Professional", "Executive", "Engineer", "Technician"];
  return (specialists[Math.floor(Math.random() * specialists.length)]);
}
var URL = function() { return("http://www." + fake.internet.domainName() +"/"+ fake.lorem.words(1)); };
var Company = function() { return(fake.company.bsAdjective() +" "+ fake.company.bsNoun())};
var Job = function() { return(fake.company.catchPhraseAdjective() +" "+ fake.company.catchPhraseNoun() + getSpecialism()) };
var FullName = function() { return (fake.name.firstName() + " " + fake.name.lastName()) };
var fileType = "activities"; // global until the logic is added for other types

if (!process.argv[2] || isNaN(+process.argv[2])) {
  console.log("Usage: generateActivities # "); //locale import")

} else { // only write a file if the user indicates how many records
  userInput = +process.argv[2];
    fake.locale = "zh_CN"; // manual entry for now
    var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

    stream.once('open', function(fd) {
      stream.write("Unique ID,Name,Description,Activity Code,Track,Tags (comma-separated),Start Time,End Time,Location Name,Parent Activity Unique ID\n");

        for (i=0; i<userInput; i++) {
          stream.write("A-" + (i+1) + ", " + "Session " + (i+1) + ", " + fake.company.catchPhrase() + ", " + ", " + ", " + ", " + "Start Time" + ", " + "End Time" + ", " + fake.hacker.adjective() + ", " + "\n");
        }
        stream.end();
        console.log(fake.locale +"_"+ fileType + ".csv created");
    });
}
