#!/usr/bin/env node

var fake = require('faker');
var fs = require('fs');

// var All_locales = ['de', 'de_AT','de_CH','en','en_AU','en_BORK','en_CA','en_GB','en_IND','en_US','en_au_ocker','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
// var locales = ['de','en','es','fa','fr','it','ja','ko','nb_NO','nep','nl','pl','pt_BR','ru','sk','sv','vi','zh_CN'];
var RandomURL = function() { return("http://www." + fake.internet.domainName() +"/"+ fake.lorem.words(1)); };
var OddJob = function() { return(fake.company.catchPhraseAdjective() +" "+ fake.company.catchPhraseNoun() + " " + getSpecialism()) };
var FullName = function() { return (fake.name.firstName() + " " + fake.name.lastName()) };
var DisplayName = function() { return (fake.company.catchPhraseAdjective() +" "+ fake.hacker.noun())};
var CompanyName = function() { return(fake.company.bsAdjective() +" "+ fake.company.bsNoun())};
var getSpecialism = function() {
  specialists = ["Specialist", "Professional", "Executive", "Engineer", "Technician"];
  return (specialists[Math.floor(Math.random() * specialists.length)]);
}
var yesOrNo = function() {
  options = ["Yes", "No"];
  return options[Math.floor(Math.random() *2)];
}
var TrueOrFalse = function() {
  options = ["TRUE", "FALSE"];
  return options[Math.floor(Math.random() *2)];
}

var showUsage = function() {
  console.log("\nUsage: ImportGenerator # Type Locale");
  console.log("---------------------------------");
  console.log("#\t| Number of rows");
  console.log("Types\t| Activities, Appointments, Attendees, Locations, Organizations, Pages, People, Schedules, Tracks");
  console.log("Locales | en(default), de, es, fa, fr, it, ja, ko, nb_NO, nep, nl, pl, pt_BR, ru, sk, sv, vi, zh_CN");
}

var generateFile = function (file) {
    switch (file) {

        case 'Activities':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Name,Description,Activity Code,Track,Tags (comma-separated),Start Time,End Time,Location Name,Parent Activity Unique ID\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + "Session " + (i+1) + ", " + fake.company.catchPhrase() + ", " + ", " + ", " + ", " + fake.date.past() + ", " + fake.date.future() + ", " + DisplayName() + ", " + "\n");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Appointments':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Emails,Attendee Unique IDs,Appointment Name,Description,Start Time,End Time,Location Name\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + fake.internet.email() + ", " + "E-" + (i+1) + ", " + fake.company.catchPhrase() + ", " + fake.company.catchPhrase() + ", " + fake.date.past() + ", " + fake.date.future() + ", " + fake.company.catchPhrase() + "\n");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Attendees':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,First Name,Last Name,Suffix,Email,Registration Code,Show on Attendee List,Company Name,Job Title,Brief Bio,Work Phone,Mobile Phone,Other Phone,Other Phone Type,Address,Address 2,City,State,Zipcode,Country,Website,Website 2,Linkedin URL,Twitter URL,Facebook URL,Group List (comma-separated)\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + fake.name.firstName() + ", " + fake.name.lastName() + ", " + ", " + fake.internet.email() + ", " + ", " + TrueOrFalse() + ", " + CompanyName() + ", " + OddJob() + ", " + ", " + fake.phone.phoneNumber() + ", " + ", " + ", " + ", " + fake.address.streetAddress() + ", " + ", " + fake.address.city() + ", " + fake.address.state() + ", " + fake.address.zipCode() + ", " + fake.address.country() + ", " + RandomURL() + ", " + RandomURL() + ", " + ", " + ", " + ", \n");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Locations':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Name,Description,Address,Address 2,City,State,Country,Zipcode,Phone Work,Phone Mobile,Phone Other,Phone Other Type,Email,Email 2,Website,Website 2,Linkedin URL,Twitter URL,Facebook URL,Always show this location on the map?\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + FullName() + ", " + fake.company.catchPhrase() + ", " + fake.address.streetAddress() + ", " + ", " + fake.address.city() + ", " + fake.address.state() + ", " + ", " + fake.address.zipCode() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.internet.email() + ", " + fake.internet.email() + ", " + RandomURL() + ", " + RandomURL() + ", " + ", " + ", " + ", " + yesOrNo() + "\n ");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Organizations':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Organization name,Location Name,Description,Category Tags (Comma-separated),Is Highlighted?,Website,Website 2,Address,Address 2,City,State,Zipcode,Country,Phone Work,Phone Mobile,Phone Other,Phone Other Type,Email,Email 2,Linkedin URL,Twitter URL,Facebook URL,Admin Invitations (Comma-separated)\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + CompanyName() + ", " + DisplayName() + ", " + fake.company.catchPhrase() + ", " + ", " + TrueOrFalse() + ", " + RandomURL() + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", " + ", \n");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Pages':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Name,Description,Category Tags (Comma-separated),Group List (comma-separated)\n");
              for (i=0; i<userInput; i++) {
                stream.write("A-" + (i+1) + ", " + fake.name.lastName() + ", " + "<p>" + fake.company.catchPhrase() + "<br></p>" +", \n");
              }
              stream.end();
              console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'People':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,First Name,Last Name,Display Name,Title,Bio,Email,Email 2,Organization Name,Website,Website 2,Address,Address 2,City,State,Zipcode,Country,Phone Work,Phone Mobile,Phone Other,Phone Other Type,Tags (comma-separated),Linkedin URL,Twitter URL,Facebook URL,Admin Invitations (Comma-separated)\n");

              for (i=0; i<userInput; i++) {
                stream.write("A-" + (i+1) + ", " + fake.name.firstName() + ", " + fake.name.lastName() + ", " + DisplayName() + ", " + OddJob() + ", " + fake.hacker.ingverb() + ", " + fake.internet.email() + ", " + fake.internet.email() + ", " + CompanyName() + ", " + RandomURL() + ", " + RandomURL() + ", " + fake.address.streetAddress() + ", " + ", " + fake.address.city() + ", " + fake.address.state() + ", " + fake.address.zipCode() + ", " + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + fake.phone.phoneNumber() + ", " + ", " + ", " + ", " + ",\n");
              }
              stream.end();
              console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Schedules':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Email,Attendee Unique ID,Activity Unique ID,Change" + "\n");
              for (i=0; i<userInput; i++) {
                stream.write(fake.internet.email() + ", " + "U-" + (i+1) + ", " + "A-" + (i+1) + ", " + "add" +", \n");
              }
              stream.end();
              console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        case 'Tracks':
          userInput = +process.argv[2];
            var stream = fs.createWriteStream(fake.locale +"_"+ fileType + ".csv");

            stream.once('open', function(fd) {
              stream.write("Unique ID,Name,Sequence Number,Track Groups (comma-separated)\n");

                for (i=0; i<userInput; i++) {
                  stream.write("A-" + (i+1) + ", " + fake.name.lastName() + ", " + "\n");
                }
                stream.end();
                console.log(fake.locale +"_"+ fileType + ".csv created");
            });
        break;

        default:
        showUsage();
    }
};

if (!process.argv[2] || isNaN(+process.argv[2]) || !process.argv[3]) {
  showUsage();
} else { // only write a file if the user indicates how many records and file type
  fileType = process.argv[3];
  if (!process.argv[4]) { // default to 'en' if no language is entered by the user
    fake.locale = "en";
  } else {
    fake.locale = process.argv[4];
  }
  generateFile(fileType);
}
