#!/usr/bin/env node

var getReview = function (movie) {
    switch (movie) {
        case 'kittens':
        return("Purr");
        break;

        case 'puppies':
        return("Woof.");
        break;

        case 'coffee':
        return(String.fromCharCode(0x0000,0x2615));
        break;

        default:
        return("I don't know!");
    }
};

if (!process.argv[2]) {
  console.log("Usage: kittens, puppies, or coffee");
} else {
  userInput = process.argv[2];
  console.log(getReview(userInput));
}
